# Site settings
title: Anicca Chan  - Information Engineering student
description: " ..."
baseurl: "" # for test: remove string '/space-jekyll-template' to ''
url: "" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Anicca Chan 
user_title: Anicca Chan  - FrontEnd
email: k1997102454@gmail.com
twitter_username: KanzakiAria6
github_username:  AniccaChan
gplus_username:  https://twitter.com/KanzakiAria6
linkedin_public_url:  # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
disqus_username: loremipsum
profile_picture: https://i.imgur.com/JipK98t.jpg
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: 
    url: 
  - name: 
    url: 
  - name: 
    url: 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
